sudo: false
language: erlang
otp_release:
    - 17.4
    - 17.5
    - 18.0
    - 18.1
    - 18.2
    - 19.0
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
script:
  - ./rebar3 get-deps
  - ./rebar3 compile
  - ./rebar3 eunit
